### ISSUE TITLE
Build frontpage based on tranzit clusters (TC0) of merger type "cdn"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/tranzit#1]
the basic idea is to easily "store" (aka transfer) any clearnet website+content (text,colors,layout,images, but videos) to someone who "registered" via tranzit ID.
Compare: http://archive.is/

Idea for basic frontpage:
![tranzit-idea-1000](https://user-images.githubusercontent.com/20817185/38770636-349869d4-4016-11e8-9c6c-7c08173f120d.jpg)

background image for now (we can make it like wetransfer change over time with various fitting images):
![tranzit](https://user-images.githubusercontent.com/20817185/38770620-0635e300-4016-11e8-99b1-71620b3b695d.png)

**Comment by dnelband** [comment]
the problem is that due to the cross origin restriction on zeronet its not possible to load clearnet content in zeronet, but i wrote tamas about it to see how we can work around this issue
